//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from AboutStrings.resx, do not edit manually.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Ink_Canvas.Properties
{
    [CompilerGenerated]
    public static class AboutStrings
    {
        private static ResourceManager _resourceMan;
        private static CultureInfo _resourceCulture;

        public static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(_resourceMan, null))
                {
                    var temp = new ResourceManager("Ink_Canvas.Properties.AboutStrings", typeof(AboutStrings).Assembly);
                    _resourceMan = temp;
                }
                return _resourceMan;
            }
        }

        public static CultureInfo Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        public static string GetString(string key)
        {
            return ResourceManager.GetString(key, _resourceCulture);
        }

        public static string Copyright => ResourceManager.GetString(nameof(Copyright), _resourceCulture);

        public static string DevelopersLabel => ResourceManager.GetString(nameof(DevelopersLabel), _resourceCulture);

        public static string LicenseBody => ResourceManager.GetString(nameof(LicenseBody), _resourceCulture);

        public static string LicenseTitle => ResourceManager.GetString(nameof(LicenseTitle), _resourceCulture);

        public static string OpenSourceSlogan => ResourceManager.GetString(nameof(OpenSourceSlogan), _resourceCulture);

        public static string PhigrosCr => ResourceManager.GetString(nameof(PhigrosCr), _resourceCulture);

        public static string ThanksContributors => ResourceManager.GetString(nameof(ThanksContributors), _resourceCulture);

        public static string Title => ResourceManager.GetString(nameof(Title), _resourceCulture);

        public static string VersionLabel => ResourceManager.GetString(nameof(VersionLabel), _resourceCulture);

    }
}