//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from AdvancedStrings.resx, do not edit manually.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Ink_Canvas.Properties
{
    [CompilerGenerated]
    public static class AdvancedStrings
    {
        private static ResourceManager _resourceMan;
        private static CultureInfo _resourceCulture;

        public static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(_resourceMan, null))
                {
                    var temp = new ResourceManager("Ink_Canvas.Properties.AdvancedStrings", typeof(AdvancedStrings).Assembly);
                    _resourceMan = temp;
                }
                return _resourceMan;
            }
        }

        public static CultureInfo Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        public static string GetString(string key)
        {
            return ResourceManager.GetString(key, _resourceCulture);
        }

        public static string AvoidFullScreenHelper => ResourceManager.GetString(nameof(AvoidFullScreenHelper), _resourceCulture);

        public static string AvoidFullScreenHelperHint => ResourceManager.GetString(nameof(AvoidFullScreenHelperHint), _resourceCulture);

        public static string ConfirmExit => ResourceManager.GetString(nameof(ConfirmExit), _resourceCulture);

        public static string DPIChangeDetection => ResourceManager.GetString(nameof(DPIChangeDetection), _resourceCulture);

        public static string DPIChangeDetectionHint => ResourceManager.GetString(nameof(DPIChangeDetectionHint), _resourceCulture);

        public static string EdgeGestureUtil => ResourceManager.GetString(nameof(EdgeGestureUtil), _resourceCulture);

        public static string EdgeGestureUtilHint_Part1 => ResourceManager.GetString(nameof(EdgeGestureUtilHint_Part1), _resourceCulture);

        public static string EraserBindTouchHint => ResourceManager.GetString(nameof(EraserBindTouchHint), _resourceCulture);

        public static string EraserBindTouchMultiplier => ResourceManager.GetString(nameof(EraserBindTouchMultiplier), _resourceCulture);

        public static string Experimental => ResourceManager.GetString(nameof(Experimental), _resourceCulture);

        public static string FingerModeBoundsWidthHeader => ResourceManager.GetString(nameof(FingerModeBoundsWidthHeader), _resourceCulture);

        public static string ForceFullScreen => ResourceManager.GetString(nameof(ForceFullScreen), _resourceCulture);

        public static string ForceFullScreenHint => ResourceManager.GetString(nameof(ForceFullScreenHint), _resourceCulture);

        public static string FullScreenHelper => ResourceManager.GetString(nameof(FullScreenHelper), _resourceCulture);

        public static string FullScreenHelperHint => ResourceManager.GetString(nameof(FullScreenHelperHint), _resourceCulture);

        public static string LogByDate => ResourceManager.GetString(nameof(LogByDate), _resourceCulture);

        public static string Logging => ResourceManager.GetString(nameof(Logging), _resourceCulture);

        public static string LogRotateHint => ResourceManager.GetString(nameof(LogRotateHint), _resourceCulture);

        public static string NibModeBoundsWidthHeader => ResourceManager.GetString(nameof(NibModeBoundsWidthHeader), _resourceCulture);

        public static string QuadIRMode => ResourceManager.GetString(nameof(QuadIRMode), _resourceCulture);

        public static string ResolutionChangeDetection => ResourceManager.GetString(nameof(ResolutionChangeDetection), _resourceCulture);

        public static string ResolutionChangeDetectionHint => ResourceManager.GetString(nameof(ResolutionChangeDetectionHint), _resourceCulture);

        public static string SpecialScreenMode => ResourceManager.GetString(nameof(SpecialScreenMode), _resourceCulture);

        public static string Title => ResourceManager.GetString(nameof(Title), _resourceCulture);

        public static string TouchMultiplier => ResourceManager.GetString(nameof(TouchMultiplier), _resourceCulture);

        public static string TouchMultiplierCalibrateHint => ResourceManager.GetString(nameof(TouchMultiplierCalibrateHint), _resourceCulture);

        public static string TouchMultiplierHint => ResourceManager.GetString(nameof(TouchMultiplierHint), _resourceCulture);

        public static string TouchMultiplierValueHint => ResourceManager.GetString(nameof(TouchMultiplierValueHint), _resourceCulture);

        public static string Debug_ShowConsole_Desc => ResourceManager.GetString(nameof(Debug_ShowConsole_Desc), _resourceCulture);

        public static string Debug_ShowConsole_Header => ResourceManager.GetString(nameof(Debug_ShowConsole_Header), _resourceCulture);

        public static string Debug_PPTComProbe_Desc => ResourceManager.GetString(nameof(Debug_PPTComProbe_Desc), _resourceCulture);

        public static string Debug_PPTComProbe_Header => ResourceManager.GetString(nameof(Debug_PPTComProbe_Header), _resourceCulture);

        public static string Debug_PPTPreviewVisible_Desc => ResourceManager.GetString(nameof(Debug_PPTPreviewVisible_Desc), _resourceCulture);

        public static string Debug_PPTPreviewVisible_Header => ResourceManager.GetString(nameof(Debug_PPTPreviewVisible_Header), _resourceCulture);

        public static string Debug_IconSettings => ResourceManager.GetString(nameof(Debug_IconSettings), _resourceCulture);

        public static string Debug_SettingsExpanderExample => ResourceManager.GetString(nameof(Debug_SettingsExpanderExample), _resourceCulture);

        public static string Debug_CrashTest_Section => ResourceManager.GetString(nameof(Debug_CrashTest_Section), _resourceCulture);

        public static string Debug_SimulateCrash_Header => ResourceManager.GetString(nameof(Debug_SimulateCrash_Header), _resourceCulture);

        public static string Debug_SimulateCrash_Desc => ResourceManager.GetString(nameof(Debug_SimulateCrash_Desc), _resourceCulture);

        public static string Debug_SimulateCrash_Button => ResourceManager.GetString(nameof(Debug_SimulateCrash_Button), _resourceCulture);

        public static string Debug_SimulateHeartbeatTimeout_Header => ResourceManager.GetString(nameof(Debug_SimulateHeartbeatTimeout_Header), _resourceCulture);

        public static string Debug_SimulateHeartbeatTimeout_Desc => ResourceManager.GetString(nameof(Debug_SimulateHeartbeatTimeout_Desc), _resourceCulture);

        public static string Debug_SimulateHeartbeatTimeout_Button => ResourceManager.GetString(nameof(Debug_SimulateHeartbeatTimeout_Button), _resourceCulture);

        public static string Debug_ResetStartupCount_Header => ResourceManager.GetString(nameof(Debug_ResetStartupCount_Header), _resourceCulture);

        public static string Debug_ResetStartupCount_Desc => ResourceManager.GetString(nameof(Debug_ResetStartupCount_Desc), _resourceCulture);

        public static string Debug_ResetStartupCount_Button => ResourceManager.GetString(nameof(Debug_ResetStartupCount_Button), _resourceCulture);

        // Hand-added to mirror the four new keys appended to AdvancedStrings.resx.
        // ResXFileCodeGenerator re-runs on the next explicit resgen pass; until then the
        // XAML compiler cannot see these new keys via x:Static. They are still loaded from
        // the same ResourceManager at runtime, so once the generator is rerun these manual
        // properties are safe to delete (they will be reproduced identically).
        public static string Debug_PageTitle => ResourceManager.GetString(nameof(Debug_PageTitle), _resourceCulture);

        public static string Debug_PageHeader => ResourceManager.GetString(nameof(Debug_PageHeader), _resourceCulture);

        public static string Debug_SettingsExpanderExample_Header => ResourceManager.GetString(nameof(Debug_SettingsExpanderExample_Header), _resourceCulture);

        public static string Debug_SettingsExpanderExample_Desc => ResourceManager.GetString(nameof(Debug_SettingsExpanderExample_Desc), _resourceCulture);

        public static string Debug_MemoryBreakdownSection => ResourceManager.GetString(nameof(Debug_MemoryBreakdownSection), _resourceCulture);

        public static string Debug_MemoryBreakdownDump_Header => ResourceManager.GetString(nameof(Debug_MemoryBreakdownDump_Header), _resourceCulture);

        public static string Debug_MemoryBreakdownDump_Desc => ResourceManager.GetString(nameof(Debug_MemoryBreakdownDump_Desc), _resourceCulture);

        public static string Debug_MemoryBreakdownDump_Button => ResourceManager.GetString(nameof(Debug_MemoryBreakdownDump_Button), _resourceCulture);

        public static string Debug_MemoryBreakdownForceGC_Header => ResourceManager.GetString(nameof(Debug_MemoryBreakdownForceGC_Header), _resourceCulture);

        public static string Debug_MemoryBreakdownForceGC_Desc => ResourceManager.GetString(nameof(Debug_MemoryBreakdownForceGC_Desc), _resourceCulture);

        public static string Debug_MemoryBreakdownForceGC_Button => ResourceManager.GetString(nameof(Debug_MemoryBreakdownForceGC_Button), _resourceCulture);
    }
}