//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from CrashStrings.resx, do not edit manually.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Ink_Canvas.Properties
{
    [CompilerGenerated]
    public static class CrashStrings
    {
        private static ResourceManager _resourceMan;
        private static CultureInfo _resourceCulture;

        public static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(_resourceMan, null))
                {
                    var temp = new ResourceManager("Ink_Canvas.Properties.CrashStrings", typeof(CrashStrings).Assembly);
                    _resourceMan = temp;
                }
                return _resourceMan;
            }
        }

        public static CultureInfo Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        public static string GetString(string key)
        {
            return ResourceManager.GetString(key, _resourceCulture);
        }

        public static string Msg_RestartLimit => ResourceManager.GetString(nameof(Msg_RestartLimit), _resourceCulture);

        public static string Msg_RestartLimitTitle => ResourceManager.GetString(nameof(Msg_RestartLimitTitle), _resourceCulture);

        public static string Crash_Desc => ResourceManager.GetString(nameof(Crash_Desc), _resourceCulture);

        public static string Crash_NoAction => ResourceManager.GetString(nameof(Crash_NoAction), _resourceCulture);

        public static string Crash_ShowCrashWindow => ResourceManager.GetString(nameof(Crash_ShowCrashWindow), _resourceCulture);

        public static string Crash_SilentRestart => ResourceManager.GetString(nameof(Crash_SilentRestart), _resourceCulture);

        public static string Crash_Title => ResourceManager.GetString(nameof(Crash_Title), _resourceCulture);

        public static string CrashWindowTitle => ResourceManager.GetString(nameof(CrashWindowTitle), _resourceCulture);

        public static string CrashWindowHeader => ResourceManager.GetString(nameof(CrashWindowHeader), _resourceCulture);

        public static string CrashWindowDescription => ResourceManager.GetString(nameof(CrashWindowDescription), _resourceCulture);

        public static string CrashWindowFooter => ResourceManager.GetString(nameof(CrashWindowFooter), _resourceCulture);

        public static string CrashWindowCopy => ResourceManager.GetString(nameof(CrashWindowCopy), _resourceCulture);

        public static string CrashWindowClose => ResourceManager.GetString(nameof(CrashWindowClose), _resourceCulture);

        public static string CrashWindowNoDetails => ResourceManager.GetString(nameof(CrashWindowNoDetails), _resourceCulture);
    }
}