//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from FeedbackStrings.resx, do not edit manually.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Ink_Canvas.Properties
{
    [CompilerGenerated]
    public static class FeedbackStrings
    {
        private static ResourceManager _resourceMan;
        private static CultureInfo _resourceCulture;

        public static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(_resourceMan, null))
                {
                    var temp = new ResourceManager("Ink_Canvas.Properties.FeedbackStrings", typeof(FeedbackStrings).Assembly);
                    _resourceMan = temp;
                }
                return _resourceMan;
            }
        }

        public static CultureInfo Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        public static string GetString(string key)
        {
            return ResourceManager.GetString(key, _resourceCulture);
        }

        public static string WindowTitle => ResourceManager.GetString(nameof(WindowTitle), _resourceCulture);

        public static string BtnCancel => ResourceManager.GetString(nameof(BtnCancel), _resourceCulture);

        public static string BtnNext => ResourceManager.GetString(nameof(BtnNext), _resourceCulture);

        public static string BtnBack => ResourceManager.GetString(nameof(BtnBack), _resourceCulture);

        public static string BtnConfirm => ResourceManager.GetString(nameof(BtnConfirm), _resourceCulture);

        public static string Page1Title => ResourceManager.GetString(nameof(Page1Title), _resourceCulture);

        public static string Page1_SoftwareInfo => ResourceManager.GetString(nameof(Page1_SoftwareInfo), _resourceCulture);

        public static string Page1_SoftwareInfoDesc => ResourceManager.GetString(nameof(Page1_SoftwareInfoDesc), _resourceCulture);

        public static string Page1_AppVersion => ResourceManager.GetString(nameof(Page1_AppVersion), _resourceCulture);


        public static string Page1_SystemInfo => ResourceManager.GetString(nameof(Page1_SystemInfo), _resourceCulture);

        public static string Page1_SystemInfoDesc => ResourceManager.GetString(nameof(Page1_SystemInfoDesc), _resourceCulture);

        public static string Page1_OSVersion => ResourceManager.GetString(nameof(Page1_OSVersion), _resourceCulture);

        public static string Page1_NetVersion => ResourceManager.GetString(nameof(Page1_NetVersion), _resourceCulture);

        public static string Page1_Config => ResourceManager.GetString(nameof(Page1_Config), _resourceCulture);

        public static string Page1_ConfigDesc => ResourceManager.GetString(nameof(Page1_ConfigDesc), _resourceCulture);

        public static string Page1_PPTSettings => ResourceManager.GetString(nameof(Page1_PPTSettings), _resourceCulture);

        public static string Page1_InkRecognition => ResourceManager.GetString(nameof(Page1_InkRecognition), _resourceCulture);

        public static string Page2Title => ResourceManager.GetString(nameof(Page2Title), _resourceCulture);

        public static string Page2_SoftwareInfo => ResourceManager.GetString(nameof(Page2_SoftwareInfo), _resourceCulture);

        public static string Page2_SoftwareInfoDesc => ResourceManager.GetString(nameof(Page2_SoftwareInfoDesc), _resourceCulture);

        public static string Page2_SystemInfo => ResourceManager.GetString(nameof(Page2_SystemInfo), _resourceCulture);

        public static string Page2_SystemInfoDesc => ResourceManager.GetString(nameof(Page2_SystemInfoDesc), _resourceCulture);

        public static string Page2_Config => ResourceManager.GetString(nameof(Page2_Config), _resourceCulture);

        public static string Page2_ConfigDesc => ResourceManager.GetString(nameof(Page2_ConfigDesc), _resourceCulture);

        public static string Page3Title => ResourceManager.GetString(nameof(Page3Title), _resourceCulture);

        public static string Page3_GitHub => ResourceManager.GetString(nameof(Page3_GitHub), _resourceCulture);

        public static string Page3_GitHubDesc => ResourceManager.GetString(nameof(Page3_GitHubDesc), _resourceCulture);

        public static string Page3_OpenGitHub => ResourceManager.GetString(nameof(Page3_OpenGitHub), _resourceCulture);

        public static string Page3_CopyIssueUrl => ResourceManager.GetString(nameof(Page3_CopyIssueUrl), _resourceCulture);

        public static string Page3_Copied => ResourceManager.GetString(nameof(Page3_Copied), _resourceCulture);

        public static string Page3_Markdown => ResourceManager.GetString(nameof(Page3_Markdown), _resourceCulture);

        public static string Page3_MarkdownDesc => ResourceManager.GetString(nameof(Page3_MarkdownDesc), _resourceCulture);

        public static string Page3_CopyMarkdown => ResourceManager.GetString(nameof(Page3_CopyMarkdown), _resourceCulture);

        public static string Page3_TemplatePlaceholder => ResourceManager.GetString(nameof(Page3_TemplatePlaceholder), _resourceCulture);

        public static string About_FeedbackButton => ResourceManager.GetString(nameof(About_FeedbackButton), _resourceCulture);

        public static string About_FeedbackSection => ResourceManager.GetString(nameof(About_FeedbackSection), _resourceCulture);

        public static string Page1_PastebinServer => ResourceManager.GetString(nameof(Page1_PastebinServer), _resourceCulture);

        public static string Page1_PastebinServerDesc => ResourceManager.GetString(nameof(Page1_PastebinServerDesc), _resourceCulture);

        public static string Page1_PastebinPlaceholder => ResourceManager.GetString(nameof(Page1_PastebinPlaceholder), _resourceCulture);

        public static string Page3_PastebinUpload => ResourceManager.GetString(nameof(Page3_PastebinUpload), _resourceCulture);

        public static string Page3_PastebinUploadDesc => ResourceManager.GetString(nameof(Page3_PastebinUploadDesc), _resourceCulture);

        public static string Page3_UploadToPastebin => ResourceManager.GetString(nameof(Page3_UploadToPastebin), _resourceCulture);

        public static string Page3_CopyPastebinUrl => ResourceManager.GetString(nameof(Page3_CopyPastebinUrl), _resourceCulture);

        public static string Page3_UploadSuccess => ResourceManager.GetString(nameof(Page3_UploadSuccess), _resourceCulture);

        public static string Page3_UploadFailed => ResourceManager.GetString(nameof(Page3_UploadFailed), _resourceCulture);

        public static string Page3_Uploading => ResourceManager.GetString(nameof(Page3_Uploading), _resourceCulture);

        public static string Page3_PastebinNotConfigured => ResourceManager.GetString(nameof(Page3_PastebinNotConfigured), _resourceCulture);

        public static string Page3_Feishu => ResourceManager.GetString(nameof(Page3_Feishu), _resourceCulture);

        public static string Page3_FeishuDesc => ResourceManager.GetString(nameof(Page3_FeishuDesc), _resourceCulture);

        public static string Page3_OpenFeishu => ResourceManager.GetString(nameof(Page3_OpenFeishu), _resourceCulture);

        public static string Page3_CopyFeishuUrl => ResourceManager.GetString(nameof(Page3_CopyFeishuUrl), _resourceCulture);
    }
}
