//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from HomeStrings.resx, do not edit manually.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Ink_Canvas.Properties
{
    [CompilerGenerated]
    public static class HomeStrings
    {
        private static ResourceManager _resourceMan;
        private static CultureInfo _resourceCulture;

        public static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(_resourceMan, null))
                {
                    var temp = new ResourceManager("Ink_Canvas.Properties.HomeStrings", typeof(HomeStrings).Assembly);
                    _resourceMan = temp;
                }
                return _resourceMan;
            }
        }

        public static CultureInfo Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        public static string GetString(string key)
        {
            return ResourceManager.GetString(key, _resourceCulture);
        }

        public static string Home_ExitApp => ResourceManager.GetString(nameof(Home_ExitApp), _resourceCulture);

        public static string Home_Reset => ResourceManager.GetString(nameof(Home_Reset), _resourceCulture);

        public static string Home_ResetSettings => ResourceManager.GetString(nameof(Home_ResetSettings), _resourceCulture);

        public static string Home_RestartApp => ResourceManager.GetString(nameof(Home_RestartApp), _resourceCulture);

        public static string Home_AboutApp => ResourceManager.GetString(nameof(Home_AboutApp), _resourceCulture);

        public static string Home_Basic => ResourceManager.GetString(nameof(Home_Basic), _resourceCulture);

        public static string Home_CanvasSettings => ResourceManager.GetString(nameof(Home_CanvasSettings), _resourceCulture);

        public static string Home_InkRecognitionSettings => ResourceManager.GetString(nameof(Home_InkRecognitionSettings), _resourceCulture);

        public static string Home_MainUI => ResourceManager.GetString(nameof(Home_MainUI), _resourceCulture);

        public static string Home_PPTSettings => ResourceManager.GetString(nameof(Home_PPTSettings), _resourceCulture);

        public static string Home_RandomAndTimer => ResourceManager.GetString(nameof(Home_RandomAndTimer), _resourceCulture);

        public static string Home_Title => ResourceManager.GetString(nameof(Home_Title), _resourceCulture);

        public static string Home_Toolbar => ResourceManager.GetString(nameof(Home_Toolbar), _resourceCulture);

        public static string Home_ToolbarSettings => ResourceManager.GetString(nameof(Home_ToolbarSettings), _resourceCulture);

        public static string Home_UpdateSettings => ResourceManager.GetString(nameof(Home_UpdateSettings), _resourceCulture);

        public static string Home_Window => ResourceManager.GetString(nameof(Home_Window), _resourceCulture);

        public static string Home_WindowSettings => ResourceManager.GetString(nameof(Home_WindowSettings), _resourceCulture);

        public static string Home_ClockSettings => ResourceManager.GetString(nameof(Home_ClockSettings), _resourceCulture);

        public static string Home_BackupSettings => ResourceManager.GetString(nameof(Home_BackupSettings), _resourceCulture);

        public static string Home_BoardSettings => ResourceManager.GetString(nameof(Home_BoardSettings), _resourceCulture);

        public static string Splash_Starting => ResourceManager.GetString(nameof(Splash_Starting), _resourceCulture);
    }
}