//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from MainWindowStrings.resx, do not edit manually.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Ink_Canvas.Properties
{
    [CompilerGenerated]
    public static class MainWindowStrings
    {
        private static ResourceManager _resourceMan;
        private static CultureInfo _resourceCulture;

        public static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(_resourceMan, null))
                {
                    var temp = new ResourceManager("Ink_Canvas.Properties.MainWindowStrings", typeof(MainWindowStrings).Assembly);
                    _resourceMan = temp;
                }
                return _resourceMan;
            }
        }

        public static CultureInfo Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        public static string GetString(string key)
        {
            return ResourceManager.GetString(key, _resourceCulture);
        }

        public static string Main_WatermarkText => ResourceManager.GetString(nameof(Main_WatermarkText), _resourceCulture);

        public static string Main_ContextClone => ResourceManager.GetString(nameof(Main_ContextClone), _resourceCulture);

        public static string Main_ContextCloneToNewPage => ResourceManager.GetString(nameof(Main_ContextCloneToNewPage), _resourceCulture);

        public static string Main_ContextFlip => ResourceManager.GetString(nameof(Main_ContextFlip), _resourceCulture);

        public static string Main_ContextBrushSize => ResourceManager.GetString(nameof(Main_ContextBrushSize), _resourceCulture);

        public static string Main_ContextDelete => ResourceManager.GetString(nameof(Main_ContextDelete), _resourceCulture);

        public static string Main_ContextZoom => ResourceManager.GetString(nameof(Main_ContextZoom), _resourceCulture);

        public static string Main_ContextPageTurn => ResourceManager.GetString(nameof(Main_ContextPageTurn), _resourceCulture);

        public static string Main_ContextInsertToWhiteboard => ResourceManager.GetString(nameof(Main_ContextInsertToWhiteboard), _resourceCulture);

        public static string Main_InkReplayPlaying => ResourceManager.GetString(nameof(Main_InkReplayPlaying), _resourceCulture);

        public static string Main_InkReplayExitHint => ResourceManager.GetString(nameof(Main_InkReplayExitHint), _resourceCulture);
        public static string Main_Strokes_SaveSuccess => ResourceManager.GetString(nameof(Main_Strokes_SaveSuccess), _resourceCulture);

        public static string Main_Strokes_SaveFailed => ResourceManager.GetString(nameof(Main_Strokes_SaveFailed), _resourceCulture);

        public static string Main_Strokes_OpenFailed => ResourceManager.GetString(nameof(Main_Strokes_OpenFailed), _resourceCulture);

        public static string Main_Strokes_OpenIccSuccess => ResourceManager.GetString(nameof(Main_Strokes_OpenIccSuccess), _resourceCulture);

        public static string Main_Strokes_OpenFileDialogTitle => ResourceManager.GetString(nameof(Main_Strokes_OpenFileDialogTitle), _resourceCulture);

        public static string Main_Strokes_OpenFileDialogFilter => ResourceManager.GetString(nameof(Main_Strokes_OpenFileDialogFilter), _resourceCulture);

        public static string Main_Strokes_SaveMultiPageXmlSuccess => ResourceManager.GetString(nameof(Main_Strokes_SaveMultiPageXmlSuccess), _resourceCulture);

        public static string Main_Strokes_SaveXmlSuccess => ResourceManager.GetString(nameof(Main_Strokes_SaveXmlSuccess), _resourceCulture);

        public static string Main_Strokes_SaveMultiPageIcstkSuccess => ResourceManager.GetString(nameof(Main_Strokes_SaveMultiPageIcstkSuccess), _resourceCulture);

        public static string Main_Strokes_SaveMultiPageXmlZipSuccess => ResourceManager.GetString(nameof(Main_Strokes_SaveMultiPageXmlZipSuccess), _resourceCulture);

        public static string Main_Strokes_SaveMultiPageZipSuccess => ResourceManager.GetString(nameof(Main_Strokes_SaveMultiPageZipSuccess), _resourceCulture);

        public static string Main_Strokes_SaveFullPageSuccess => ResourceManager.GetString(nameof(Main_Strokes_SaveFullPageSuccess), _resourceCulture);

        public static string Main_Strokes_ModeMismatch => ResourceManager.GetString(nameof(Main_Strokes_ModeMismatch), _resourceCulture);

        public static string Main_Strokes_SaveUInkSuccess => ResourceManager.GetString(nameof(Main_Strokes_SaveUInkSuccess), _resourceCulture);

        public static string Main_Strokes_SaveUInkFailed => ResourceManager.GetString(nameof(Main_Strokes_SaveUInkFailed), _resourceCulture);

        public static string Main_Strokes_OpenUInkSuccess => ResourceManager.GetString(nameof(Main_Strokes_OpenUInkSuccess), _resourceCulture);

        public static string Main_Strokes_UInkInvalid => ResourceManager.GetString(nameof(Main_Strokes_UInkInvalid), _resourceCulture);

        public static string Main_Freeze_PageFrozen => ResourceManager.GetString(nameof(Main_Freeze_PageFrozen), _resourceCulture);

        public static string Main_Freeze_AnnotationPageFrozen => ResourceManager.GetString(nameof(Main_Freeze_AnnotationPageFrozen), _resourceCulture);

        public static string Main_Freeze_WhiteboardPageFrozen => ResourceManager.GetString(nameof(Main_Freeze_WhiteboardPageFrozen), _resourceCulture);

        public static string Main_Freeze_PageUnfrozen => ResourceManager.GetString(nameof(Main_Freeze_PageUnfrozen), _resourceCulture);

        public static string Main_Freeze_WhiteboardPageUnfrozen => ResourceManager.GetString(nameof(Main_Freeze_WhiteboardPageUnfrozen), _resourceCulture);

        public static string Main_Freeze_VerifyTitle => ResourceManager.GetString(nameof(Main_Freeze_VerifyTitle), _resourceCulture);

        public static string Main_Freeze_VerifyMessage => ResourceManager.GetString(nameof(Main_Freeze_VerifyMessage), _resourceCulture);

        public static string Main_Freeze_VerifyFailed => ResourceManager.GetString(nameof(Main_Freeze_VerifyFailed), _resourceCulture);

        public static string Main_Freeze_FrozenNoEdit => ResourceManager.GetString(nameof(Main_Freeze_FrozenNoEdit), _resourceCulture);

        public static string Main_Freeze_FrozenNoAction => ResourceManager.GetString(nameof(Main_Freeze_FrozenNoAction), _resourceCulture);

        public static string Main_Freeze_Recorded => ResourceManager.GetString(nameof(Main_Freeze_Recorded), _resourceCulture);

        public static string Main_Freeze_RecordedWhiteboard => ResourceManager.GetString(nameof(Main_Freeze_RecordedWhiteboard), _resourceCulture);

        public static string Main_Freeze_CancelCountdown => ResourceManager.GetString(nameof(Main_Freeze_CancelCountdown), _resourceCulture);

        public static string Main_Freeze_CancelByOperation => ResourceManager.GetString(nameof(Main_Freeze_CancelByOperation), _resourceCulture);

        public static string Main_Freeze_AutoFreezeIn3Min => ResourceManager.GetString(nameof(Main_Freeze_AutoFreezeIn3Min), _resourceCulture);

        public static string Main_Screenshot_SaveSuccess => ResourceManager.GetString(nameof(Main_Screenshot_SaveSuccess), _resourceCulture);

        public static string Main_Screenshot_Cancelled => ResourceManager.GetString(nameof(Main_Screenshot_Cancelled), _resourceCulture);

        public static string Main_Screenshot_NoValidArea => ResourceManager.GetString(nameof(Main_Screenshot_NoValidArea), _resourceCulture);

        public static string Main_Screenshot_Failed => ResourceManager.GetString(nameof(Main_Screenshot_Failed), _resourceCulture);

        public static string Main_Screenshot_FailedWithError => ResourceManager.GetString(nameof(Main_Screenshot_FailedWithError), _resourceCulture);

        public static string Main_Screenshot_ConvertFailed => ResourceManager.GetString(nameof(Main_Screenshot_ConvertFailed), _resourceCulture);

        public static string Main_ImageInsert_ScreenshotCancelled => ResourceManager.GetString(nameof(Main_ImageInsert_ScreenshotCancelled), _resourceCulture);

        public static string Main_ImageInsert_ScreenshotFailed => ResourceManager.GetString(nameof(Main_ImageInsert_ScreenshotFailed), _resourceCulture);

        public static string Main_ImageInsert_FullScreenFailed => ResourceManager.GetString(nameof(Main_ImageInsert_FullScreenFailed), _resourceCulture);

        public static string Main_ImageInsert_InvalidScreenshot => ResourceManager.GetString(nameof(Main_ImageInsert_InvalidScreenshot), _resourceCulture);

        public static string Main_ImageInsert_ConvertFailed => ResourceManager.GetString(nameof(Main_ImageInsert_ConvertFailed), _resourceCulture);

        public static string Main_ImageInsert_Inserted => ResourceManager.GetString(nameof(Main_ImageInsert_Inserted), _resourceCulture);

        public static string Main_ImageInsert_InsertFailed => ResourceManager.GetString(nameof(Main_ImageInsert_InsertFailed), _resourceCulture);

        public static string Main_Clipboard_ImageDetected => ResourceManager.GetString(nameof(Main_Clipboard_ImageDetected), _resourceCulture);

        public static string Main_Clipboard_PasteImage => ResourceManager.GetString(nameof(Main_Clipboard_PasteImage), _resourceCulture);

        public static string Main_Clipboard_NoImage => ResourceManager.GetString(nameof(Main_Clipboard_NoImage), _resourceCulture);

        public static string Main_Clipboard_CannotGetImage => ResourceManager.GetString(nameof(Main_Clipboard_CannotGetImage), _resourceCulture);

        public static string Main_Clipboard_ImagePasted => ResourceManager.GetString(nameof(Main_Clipboard_ImagePasted), _resourceCulture);

        public static string Main_Clipboard_PasteFailed => ResourceManager.GetString(nameof(Main_Clipboard_PasteFailed), _resourceCulture);

        public static string Main_Hitokoto_Loading => ResourceManager.GetString(nameof(Main_Hitokoto_Loading), _resourceCulture);

        public static string Main_Hitokoto_Unavailable => ResourceManager.GetString(nameof(Main_Hitokoto_Unavailable), _resourceCulture);

        public static string Main_Hitokoto_HttpUnavailable => ResourceManager.GetString(nameof(Main_Hitokoto_HttpUnavailable), _resourceCulture);

        public static string Main_Hitokoto_NoContent => ResourceManager.GetString(nameof(Main_Hitokoto_NoContent), _resourceCulture);

        public static string Main_Settings_ResetVerify => ResourceManager.GetString(nameof(Main_Settings_ResetVerify), _resourceCulture);

        public static string Main_Settings_ResetVerifyMessage => ResourceManager.GetString(nameof(Main_Settings_ResetVerifyMessage), _resourceCulture);

        public static string Main_Settings_ResetDone => ResourceManager.GetString(nameof(Main_Settings_ResetDone), _resourceCulture);

        public static string Main_Uri_EnterFoldMode => ResourceManager.GetString(nameof(Main_Uri_EnterFoldMode), _resourceCulture);

        public static string Main_Uri_ExitFoldMode => ResourceManager.GetString(nameof(Main_Uri_ExitFoldMode), _resourceCulture);

        public static string Main_Uri_HideOnFoldEnabled => ResourceManager.GetString(nameof(Main_Uri_HideOnFoldEnabled), _resourceCulture);

        public static string Main_Uri_HideOnFoldDisabled => ResourceManager.GetString(nameof(Main_Uri_HideOnFoldDisabled), _resourceCulture);

        public static string Main_Uri_SchemeNotFound => ResourceManager.GetString(nameof(Main_Uri_SchemeNotFound), _resourceCulture);

        public static string Main_Uri_SwitchedScheme => ResourceManager.GetString(nameof(Main_Uri_SwitchedScheme), _resourceCulture);

        public static string Main_Uri_Restart => ResourceManager.GetString(nameof(Main_Uri_Restart), _resourceCulture);

        public static string Main_Uri_RestartAdmin => ResourceManager.GetString(nameof(Main_Uri_RestartAdmin), _resourceCulture);

        public static string Main_Uri_RestartNormal => ResourceManager.GetString(nameof(Main_Uri_RestartNormal), _resourceCulture);

        public static string Main_Uri_Exit => ResourceManager.GetString(nameof(Main_Uri_Exit), _resourceCulture);

        public static string Main_Uri_ClearInk => ResourceManager.GetString(nameof(Main_Uri_ClearInk), _resourceCulture);

        public static string Main_Uri_ClearInkAndHistory => ResourceManager.GetString(nameof(Main_Uri_ClearInkAndHistory), _resourceCulture);

        public static string Main_Uri_Undo => ResourceManager.GetString(nameof(Main_Uri_Undo), _resourceCulture);

        public static string Main_Uri_Redo => ResourceManager.GetString(nameof(Main_Uri_Redo), _resourceCulture);

        public static string Main_Uri_NextPage => ResourceManager.GetString(nameof(Main_Uri_NextPage), _resourceCulture);

        public static string Main_Uri_PreviousPage => ResourceManager.GetString(nameof(Main_Uri_PreviousPage), _resourceCulture);

        public static string Main_Uri_NewPage => ResourceManager.GetString(nameof(Main_Uri_NewPage), _resourceCulture);

        public static string Main_Uri_DeletePage => ResourceManager.GetString(nameof(Main_Uri_DeletePage), _resourceCulture);

        public static string Main_Uri_Screenshot => ResourceManager.GetString(nameof(Main_Uri_Screenshot), _resourceCulture);

        public static string Main_Tray_ExitFoldMode => ResourceManager.GetString(nameof(Main_Tray_ExitFoldMode), _resourceCulture);

        public static string Main_Tray_EnterFoldMode => ResourceManager.GetString(nameof(Main_Tray_EnterFoldMode), _resourceCulture);

        public static string Main_Tray_DisableHotkeys => ResourceManager.GetString(nameof(Main_Tray_DisableHotkeys), _resourceCulture);

        public static string Main_Tray_EnableHotkeys => ResourceManager.GetString(nameof(Main_Tray_EnableHotkeys), _resourceCulture);

        public static string Main_Colors_DarkTheme => ResourceManager.GetString(nameof(Main_Colors_DarkTheme), _resourceCulture);

        public static string Main_Colors_LightTheme => ResourceManager.GetString(nameof(Main_Colors_LightTheme), _resourceCulture);

        public static string Main_RollCall_CannotCallExternal => ResourceManager.GetString(nameof(Main_RollCall_CannotCallExternal), _resourceCulture);

        public static string Main_InkReplay_Paused => ResourceManager.GetString(nameof(Main_InkReplay_Paused), _resourceCulture);

        public static string Main_CloseConfirm_Level1 => ResourceManager.GetString(nameof(Main_CloseConfirm_Level1), _resourceCulture);

        public static string Main_CloseConfirm_Level2 => ResourceManager.GetString(nameof(Main_CloseConfirm_Level2), _resourceCulture);

        public static string Main_CloseConfirm_Level3 => ResourceManager.GetString(nameof(Main_CloseConfirm_Level3), _resourceCulture);

        public static string Main_EnterSettings => ResourceManager.GetString(nameof(Main_EnterSettings), _resourceCulture);

        public static string Main_EnterSettings_Message => ResourceManager.GetString(nameof(Main_EnterSettings_Message), _resourceCulture);

        public static string Main_AutoFold_ClearingAndFolding => ResourceManager.GetString(nameof(Main_AutoFold_ClearingAndFolding), _resourceCulture);

        public static string Main_FileInsert_OpenDialogFilter => ResourceManager.GetString(nameof(Main_FileInsert_OpenDialogFilter), _resourceCulture);

        public static string Main_MediaInsert_OpenDialogFilter => ResourceManager.GetString(nameof(Main_MediaInsert_OpenDialogFilter), _resourceCulture);

        public static string Main_MediaInsert_UnsupportedFormat => ResourceManager.GetString(nameof(Main_MediaInsert_UnsupportedFormat), _resourceCulture);

        public static string Main_MediaInsert_InsertFailed => ResourceManager.GetString(nameof(Main_MediaInsert_InsertFailed), _resourceCulture);

        public static string Main_PDF_InsertFailed => ResourceManager.GetString(nameof(Main_PDF_InsertFailed), _resourceCulture);

        public static string Main_Board_FrozenCannotDelete => ResourceManager.GetString(nameof(Main_Board_FrozenCannotDelete), _resourceCulture);
        public static string Main_Board_CustomBgApplied => ResourceManager.GetString(nameof(Main_Board_CustomBgApplied), _resourceCulture);

        public static string Main_Timer_AutoClosedInkeys => ResourceManager.GetString(nameof(Main_Timer_AutoClosedInkeys), _resourceCulture);

        public static string Main_Timer_AutoClosedYouJiao => ResourceManager.GetString(nameof(Main_Timer_AutoClosedYouJiao), _resourceCulture);

        public static string Main_Timer_AutoClosedSeewoDesktop => ResourceManager.GetString(nameof(Main_Timer_AutoClosedSeewoDesktop), _resourceCulture);

        public static string Main_Security_Tip => ResourceManager.GetString(nameof(Main_Security_Tip), _resourceCulture);

        public static string Main_Security_PasswordTooShort => ResourceManager.GetString(nameof(Main_Security_PasswordTooShort), _resourceCulture);

        public static string Main_Security_PasswordMismatch => ResourceManager.GetString(nameof(Main_Security_PasswordMismatch), _resourceCulture);

        public static string Main_Security_CurrentPasswordWrong => ResourceManager.GetString(nameof(Main_Security_CurrentPasswordWrong), _resourceCulture);

        public static string Main_Security_NewPasswordTooShort => ResourceManager.GetString(nameof(Main_Security_NewPasswordTooShort), _resourceCulture);

        public static string Main_Security_NewPasswordMismatch => ResourceManager.GetString(nameof(Main_Security_NewPasswordMismatch), _resourceCulture);

        public static string Main_Security_SetPasswordTitle => ResourceManager.GetString(nameof(Main_Security_SetPasswordTitle), _resourceCulture);

        public static string Main_Security_ChangePasswordTitle => ResourceManager.GetString(nameof(Main_Security_ChangePasswordTitle), _resourceCulture);

        public static string Main_Security_EnterNewPassword => ResourceManager.GetString(nameof(Main_Security_EnterNewPassword), _resourceCulture);

        public static string Main_Security_NewPasswordLabel => ResourceManager.GetString(nameof(Main_Security_NewPasswordLabel), _resourceCulture);

        public static string Main_Security_ConfirmNewPasswordLabel => ResourceManager.GetString(nameof(Main_Security_ConfirmNewPasswordLabel), _resourceCulture);

        public static string Main_Security_CurrentPasswordLabel => ResourceManager.GetString(nameof(Main_Security_CurrentPasswordLabel), _resourceCulture);

        public static string Main_Security_ChangePasswordHint => ResourceManager.GetString(nameof(Main_Security_ChangePasswordHint), _resourceCulture);

        public static string Main_Security_TotpOnlyHint => ResourceManager.GetString(nameof(Main_Security_TotpOnlyHint), _resourceCulture);

        public static string Main_Security_PasswordOrTotpHint => ResourceManager.GetString(nameof(Main_Security_PasswordOrTotpHint), _resourceCulture);

        public static string Main_Security_PasswordOnlyHint => ResourceManager.GetString(nameof(Main_Security_PasswordOnlyHint), _resourceCulture);

        public static string Main_Update_FailedTitle => ResourceManager.GetString(nameof(Main_Update_FailedTitle), _resourceCulture);

        public static string Main_Update_FilesInUse => ResourceManager.GetString(nameof(Main_Update_FilesInUse), _resourceCulture);

        public static string Main_Update_CopyError => ResourceManager.GetString(nameof(Main_Update_CopyError), _resourceCulture);

        public static string Main_Update_LaunchFailedTitle => ResourceManager.GetString(nameof(Main_Update_LaunchFailedTitle), _resourceCulture);

        public static string Main_Update_LaunchFailed => ResourceManager.GetString(nameof(Main_Update_LaunchFailed), _resourceCulture);

        public static string Main_Update_LaunchNotFoundTitle => ResourceManager.GetString(nameof(Main_Update_LaunchNotFoundTitle), _resourceCulture);

        public static string Main_Update_LaunchNotFound => ResourceManager.GetString(nameof(Main_Update_LaunchNotFound), _resourceCulture);

        public static string Main_Update_Failed => ResourceManager.GetString(nameof(Main_Update_Failed), _resourceCulture);

        public static string Main_Screenshot_DragToSelect => ResourceManager.GetString(nameof(Main_Screenshot_DragToSelect), _resourceCulture);

        public static string Main_Screenshot_FreeDrawHint => ResourceManager.GetString(nameof(Main_Screenshot_FreeDrawHint), _resourceCulture);

        public static string Main_Screenshot_CameraMode => ResourceManager.GetString(nameof(Main_Screenshot_CameraMode), _resourceCulture);

        public static string Main_Screenshot_NoCamera => ResourceManager.GetString(nameof(Main_Screenshot_NoCamera), _resourceCulture);

        public static string Main_Screenshot_CameraStartFailed => ResourceManager.GetString(nameof(Main_Screenshot_CameraStartFailed), _resourceCulture);

        public static string Main_Screenshot_CameraFrameFailed => ResourceManager.GetString(nameof(Main_Screenshot_CameraFrameFailed), _resourceCulture);

        public static string Main_Screenshot_CameraNotStarted => ResourceManager.GetString(nameof(Main_Screenshot_CameraNotStarted), _resourceCulture);

        public static string Main_Screenshot_CameraCaptureFailed => ResourceManager.GetString(nameof(Main_Screenshot_CameraCaptureFailed), _resourceCulture);

        public static string Main_Screenshot_FreeSelectDone => ResourceManager.GetString(nameof(Main_Screenshot_FreeSelectDone), _resourceCulture);

        public static string Main_Screenshot_FreeSelectTooSmall => ResourceManager.GetString(nameof(Main_Screenshot_FreeSelectTooSmall), _resourceCulture);

        public static string Main_Screenshot_DragToAdjust => ResourceManager.GetString(nameof(Main_Screenshot_DragToAdjust), _resourceCulture);

        public static string Main_Screenshot_DragToSelectArea => ResourceManager.GetString(nameof(Main_Screenshot_DragToSelectArea), _resourceCulture);

        public static string Main_Screenshot_SelectFirst => ResourceManager.GetString(nameof(Main_Screenshot_SelectFirst), _resourceCulture);

        public static string Main_Screenshot_DrawFirst => ResourceManager.GetString(nameof(Main_Screenshot_DrawFirst), _resourceCulture);

        public static string Main_Screenshot_FullScreenSelected => ResourceManager.GetString(nameof(Main_Screenshot_FullScreenSelected), _resourceCulture);

        public static string Main_Screenshot_NoInkPreview => ResourceManager.GetString(nameof(Main_Screenshot_NoInkPreview), _resourceCulture);

        public static string Main_Screenshot_CameraConnected => ResourceManager.GetString(nameof(Main_Screenshot_CameraConnected), _resourceCulture);

        public static string Main_Screenshot_CameraError => ResourceManager.GetString(nameof(Main_Screenshot_CameraError), _resourceCulture);

        public static string Main_Screenshot_WindowTitle => ResourceManager.GetString(nameof(Main_Screenshot_WindowTitle), _resourceCulture);

        public static string Main_Screenshot_RectangleMode => ResourceManager.GetString(nameof(Main_Screenshot_RectangleMode), _resourceCulture);

        public static string Main_Screenshot_FreehandMode => ResourceManager.GetString(nameof(Main_Screenshot_FreehandMode), _resourceCulture);

        public static string Main_Screenshot_FullScreenMode => ResourceManager.GetString(nameof(Main_Screenshot_FullScreenMode), _resourceCulture);

        public static string Main_Screenshot_CameraCaptureMode => ResourceManager.GetString(nameof(Main_Screenshot_CameraCaptureMode), _resourceCulture);

        public static string Main_Screenshot_IncludeInk => ResourceManager.GetString(nameof(Main_Screenshot_IncludeInk), _resourceCulture);

        public static string Main_Screenshot_ConfirmCapture => ResourceManager.GetString(nameof(Main_Screenshot_ConfirmCapture), _resourceCulture);

        public static string Main_Screenshot_AddToWhiteboard => ResourceManager.GetString(nameof(Main_Screenshot_AddToWhiteboard), _resourceCulture);

        public static string Main_Screenshot_SwitchCamera => ResourceManager.GetString(nameof(Main_Screenshot_SwitchCamera), _resourceCulture);

        public static string Main_Screenshot_Rotation => ResourceManager.GetString(nameof(Main_Screenshot_Rotation), _resourceCulture);

        public static string Main_Screenshot_Resolution => ResourceManager.GetString(nameof(Main_Screenshot_Resolution), _resourceCulture);

        public static string Main_Screenshot_CameraNotConnected => ResourceManager.GetString(nameof(Main_Screenshot_CameraNotConnected), _resourceCulture);

        public static string Main_Screenshot_DefaultHint => ResourceManager.GetString(nameof(Main_Screenshot_DefaultHint), _resourceCulture);

        public static string Main_App_RestartLoopDetected => ResourceManager.GetString(nameof(Main_App_RestartLoopDetected), _resourceCulture);

        public static string Main_App_UnexpectedError => ResourceManager.GetString(nameof(Main_App_UnexpectedError), _resourceCulture);

        public static string Main_DisplayChanged => ResourceManager.GetString(nameof(Main_DisplayChanged), _resourceCulture);

        public static string Main_DPIChanged => ResourceManager.GetString(nameof(Main_DPIChanged), _resourceCulture);

        public static string Main_StrokesFileLoaded => ResourceManager.GetString(nameof(Main_StrokesFileLoaded), _resourceCulture);

        public static string Main_StrokesFileOpenFailed => ResourceManager.GetString(nameof(Main_StrokesFileOpenFailed), _resourceCulture);

        public static string Main_ExitVerify => ResourceManager.GetString(nameof(Main_ExitVerify), _resourceCulture);

        public static string Main_ExitVerifyWithTotp => ResourceManager.GetString(nameof(Main_ExitVerifyWithTotp), _resourceCulture);

        public static string Main_ExitVerifyPasswordOnly => ResourceManager.GetString(nameof(Main_ExitVerifyPasswordOnly), _resourceCulture);
    }
}
