//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from NavStrings.resx, do not edit manually.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Ink_Canvas.Properties
{
    [CompilerGenerated]
    public static class NavStrings
    {
        private static ResourceManager _resourceMan;
        private static CultureInfo _resourceCulture;

        public static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(_resourceMan, null))
                {
                    var temp = new ResourceManager("Ink_Canvas.Properties.NavStrings", typeof(NavStrings).Assembly);
                    _resourceMan = temp;
                }
                return _resourceMan;
            }
        }

        public static CultureInfo Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        public static string GetString(string key)
        {
            return ResourceManager.GetString(key, _resourceCulture);
        }

        public static string Nav_Advanced => ResourceManager.GetString(nameof(Nav_Advanced), _resourceCulture);

        public static string Nav_Advanced_Settings => ResourceManager.GetString(nameof(Nav_Advanced_Settings), _resourceCulture);

        public static string Nav_Automation_Settings => ResourceManager.GetString(nameof(Nav_Automation_Settings), _resourceCulture);

        public static string Nav_PPT_Settings => ResourceManager.GetString(nameof(Nav_PPT_Settings), _resourceCulture);

        public static string Nav_Shortcuts => ResourceManager.GetString(nameof(Nav_Shortcuts), _resourceCulture);

        public static string Nav_Startup => ResourceManager.GetString(nameof(Nav_Startup), _resourceCulture);

        public static string Nav_Theme_Settings => ResourceManager.GetString(nameof(Nav_Theme_Settings), _resourceCulture);

        public static string Settings_ModeDesc => ResourceManager.GetString(nameof(Settings_ModeDesc), _resourceCulture);

        public static string Settings_ModeDesc_1 => ResourceManager.GetString(nameof(Settings_ModeDesc_1), _resourceCulture);

        public static string Settings_Nav_Hotkey_Tooltip => ResourceManager.GetString(nameof(Settings_Nav_Hotkey_Tooltip), _resourceCulture);

        public static string Settings_Nav_Security => ResourceManager.GetString(nameof(Settings_Nav_Security), _resourceCulture);

        public static string Settings_Nav_Security_Tooltip => ResourceManager.GetString(nameof(Settings_Nav_Security_Tooltip), _resourceCulture);

        public static string Settings_Title => ResourceManager.GetString(nameof(Settings_Title), _resourceCulture);

        public static string Nav_SettingsWindow_Title => ResourceManager.GetString(nameof(Nav_SettingsWindow_Title), _resourceCulture);

        public static string Nav_AppSettings => ResourceManager.GetString(nameof(Nav_AppSettings), _resourceCulture);

        public static string Nav_SearchSettings => ResourceManager.GetString(nameof(Nav_SearchSettings), _resourceCulture);

        public static string Nav_Home => ResourceManager.GetString(nameof(Nav_Home), _resourceCulture);

        public static string Nav_Home_Tooltip => ResourceManager.GetString(nameof(Nav_Home_Tooltip), _resourceCulture);

        public static string Nav_CopySettingsUri_Tooltip => ResourceManager.GetString(nameof(Nav_CopySettingsUri_Tooltip), _resourceCulture);

        public static string Nav_CopySettingsUri_Copied => ResourceManager.GetString(nameof(Nav_CopySettingsUri_Copied), _resourceCulture);

        public static string Nav_ICCSettings => ResourceManager.GetString(nameof(Nav_ICCSettings), _resourceCulture);

        public static string Nav_Basic => ResourceManager.GetString(nameof(Nav_Basic), _resourceCulture);

        public static string Nav_General => ResourceManager.GetString(nameof(Nav_General), _resourceCulture);

        public static string Nav_General_Tooltip => ResourceManager.GetString(nameof(Nav_General_Tooltip), _resourceCulture);

        public static string Nav_Startup_Tooltip => ResourceManager.GetString(nameof(Nav_Startup_Tooltip), _resourceCulture);

        public static string Nav_Clock => ResourceManager.GetString(nameof(Nav_Clock), _resourceCulture);

        public static string Nav_Clock_Tooltip => ResourceManager.GetString(nameof(Nav_Clock_Tooltip), _resourceCulture);

        public static string Nav_ToolbarComponents => ResourceManager.GetString(nameof(Nav_ToolbarComponents), _resourceCulture);

        public static string Nav_ToolbarComponents_Tooltip => ResourceManager.GetString(nameof(Nav_ToolbarComponents_Tooltip), _resourceCulture);

        public static string Nav_ToolbarAppearance => ResourceManager.GetString(nameof(Nav_ToolbarAppearance), _resourceCulture);

        public static string Nav_ToolbarAppearance_Tooltip => ResourceManager.GetString(nameof(Nav_ToolbarAppearance_Tooltip), _resourceCulture);

        public static string Nav_Basic_Tooltip => ResourceManager.GetString(nameof(Nav_Basic_Tooltip), _resourceCulture);

        public static string Nav_MainInterface => ResourceManager.GetString(nameof(Nav_MainInterface), _resourceCulture);

        public static string Nav_MainInterface_Tooltip => ResourceManager.GetString(nameof(Nav_MainInterface_Tooltip), _resourceCulture);

        public static string Nav_Window => ResourceManager.GetString(nameof(Nav_Window), _resourceCulture);

        public static string Nav_Window_Tooltip => ResourceManager.GetString(nameof(Nav_Window_Tooltip), _resourceCulture);

        public static string Nav_Sidebar => ResourceManager.GetString(nameof(Nav_Sidebar), _resourceCulture);

        public static string Nav_Sidebar_Tooltip => ResourceManager.GetString(nameof(Nav_Sidebar_Tooltip), _resourceCulture);

        public static string Nav_Toolbar => ResourceManager.GetString(nameof(Nav_Toolbar), _resourceCulture);

        public static string Nav_Toolbar_Tooltip => ResourceManager.GetString(nameof(Nav_Toolbar_Tooltip), _resourceCulture);

        public static string Nav_BoardToolbar => ResourceManager.GetString(nameof(Nav_BoardToolbar), _resourceCulture);

        public static string Nav_BoardToolbar_Tooltip => ResourceManager.GetString(nameof(Nav_BoardToolbar_Tooltip), _resourceCulture);

        public static string Nav_Board => ResourceManager.GetString(nameof(Nav_Board), _resourceCulture);

        public static string Nav_Board_Tooltip => ResourceManager.GetString(nameof(Nav_Board_Tooltip), _resourceCulture);

        public static string Nav_BoardComponents => ResourceManager.GetString(nameof(Nav_BoardComponents), _resourceCulture);

        public static string Nav_BoardComponents_Tooltip => ResourceManager.GetString(nameof(Nav_BoardComponents_Tooltip), _resourceCulture);

        public static string Nav_BoardAppearance => ResourceManager.GetString(nameof(Nav_BoardAppearance), _resourceCulture);

        public static string Nav_BoardAppearance_Tooltip => ResourceManager.GetString(nameof(Nav_BoardAppearance_Tooltip), _resourceCulture);

        public static string Nav_ToolbarMenu => ResourceManager.GetString(nameof(Nav_ToolbarMenu), _resourceCulture);

        public static string Nav_ToolbarMenu_Tooltip => ResourceManager.GetString(nameof(Nav_ToolbarMenu_Tooltip), _resourceCulture);

        public static string Nav_BoardMenu => ResourceManager.GetString(nameof(Nav_BoardMenu), _resourceCulture);

        public static string Nav_BoardMenu_Tooltip => ResourceManager.GetString(nameof(Nav_BoardMenu_Tooltip), _resourceCulture);

        public static string Nav_CanvasAndInk_Tooltip => ResourceManager.GetString(nameof(Nav_CanvasAndInk_Tooltip), _resourceCulture);

        public static string Nav_Canvas_Tooltip => ResourceManager.GetString(nameof(Nav_Canvas_Tooltip), _resourceCulture);

        public static string Nav_InkRecognition_Tooltip => ResourceManager.GetString(nameof(Nav_InkRecognition_Tooltip), _resourceCulture);

        public static string Nav_PPT_Tooltip => ResourceManager.GetString(nameof(Nav_PPT_Tooltip), _resourceCulture);

        public static string Nav_Update_Tooltip => ResourceManager.GetString(nameof(Nav_Update_Tooltip), _resourceCulture);

        public static string Nav_RandomDraw_Tooltip => ResourceManager.GetString(nameof(Nav_RandomDraw_Tooltip), _resourceCulture);

        public static string Nav_AboutInkCanvas => ResourceManager.GetString(nameof(Nav_AboutInkCanvas), _resourceCulture);

        public static string Nav_NavigateError => ResourceManager.GetString(nameof(Nav_NavigateError), _resourceCulture);

        public static string Nav_Error => ResourceManager.GetString(nameof(Nav_Error), _resourceCulture);

        public static string Nav_IndexBuildFailed => ResourceManager.GetString(nameof(Nav_IndexBuildFailed), _resourceCulture);

        public static string Nav_PreloadPageFailed => ResourceManager.GetString(nameof(Nav_PreloadPageFailed), _resourceCulture);

        public static string Nav_PreloadPagesFailed => ResourceManager.GetString(nameof(Nav_PreloadPagesFailed), _resourceCulture);

        public static string Settings_Description => ResourceManager.GetString(nameof(Settings_Description), _resourceCulture);

        public static string Nav_WhiteboardTips => ResourceManager.GetString(nameof(Nav_WhiteboardTips), _resourceCulture);

        public static string Nav_WhiteboardTips_Tooltip => ResourceManager.GetString(nameof(Nav_WhiteboardTips_Tooltip), _resourceCulture);

        public static string Menu_AddedItems => ResourceManager.GetString(nameof(Menu_AddedItems), _resourceCulture);

        public static string Menu_AvailableItems => ResourceManager.GetString(nameof(Menu_AvailableItems), _resourceCulture);

        public static string Menu_ResetLayout => ResourceManager.GetString(nameof(Menu_ResetLayout), _resourceCulture);

        public static string Menu_LimitReached => ResourceManager.GetString(nameof(Menu_LimitReached), _resourceCulture);

        public static string Menu_ResetConfirmTitle => ResourceManager.GetString(nameof(Menu_ResetConfirmTitle), _resourceCulture);

        public static string Menu_ResetConfirmMsg => ResourceManager.GetString(nameof(Menu_ResetConfirmMsg), _resourceCulture);

        public static string Menu_ResetDone => ResourceManager.GetString(nameof(Menu_ResetDone), _resourceCulture);

        public static string Menu_ToolbarDesc => ResourceManager.GetString(nameof(Menu_ToolbarDesc), _resourceCulture);

        public static string Menu_BoardDesc => ResourceManager.GetString(nameof(Menu_BoardDesc), _resourceCulture);
    }
}