//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from NotificationStrings.resx, do not edit manually.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Ink_Canvas.Properties
{
    [CompilerGenerated]
    public static class NotificationStrings
    {
        private static ResourceManager _resourceMan;
        private static CultureInfo _resourceCulture;

        public static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(_resourceMan, null))
                {
                    var temp = new ResourceManager("Ink_Canvas.Properties.NotificationStrings", typeof(NotificationStrings).Assembly);
                    _resourceMan = temp;
                }
                return _resourceMan;
            }
        }

        public static CultureInfo Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        public static string GetString(string key)
        {
            return ResourceManager.GetString(key, _resourceCulture);
        }

        public static string ActionsTitle => ResourceManager.GetString(nameof(ActionsTitle), _resourceCulture);

        public static string AnimationMode => ResourceManager.GetString(nameof(AnimationMode), _resourceCulture);

        public static string AnimationModeHint => ResourceManager.GetString(nameof(AnimationModeHint), _resourceCulture);

        public static string AnimationOff => ResourceManager.GetString(nameof(AnimationOff), _resourceCulture);

        public static string AnimationSimple => ResourceManager.GetString(nameof(AnimationSimple), _resourceCulture);

        public static string AnimationStandard => ResourceManager.GetString(nameof(AnimationStandard), _resourceCulture);

        public static string BehaviorTitle => ResourceManager.GetString(nameof(BehaviorTitle), _resourceCulture);

        public static string Close => ResourceManager.GetString(nameof(Close), _resourceCulture);

        public static string DefaultTitle => ResourceManager.GetString(nameof(DefaultTitle), _resourceCulture);

        public static string DictationDoNotDisturb => ResourceManager.GetString(nameof(DictationDoNotDisturb), _resourceCulture);

        public static string DictationDoNotDisturbHint => ResourceManager.GetString(nameof(DictationDoNotDisturbHint), _resourceCulture);

        public static string DictationDoNotDisturbPPT => ResourceManager.GetString(nameof(DictationDoNotDisturbPPT), _resourceCulture);

        public static string DictationDoNotDisturbPPTHint => ResourceManager.GetString(nameof(DictationDoNotDisturbPPTHint), _resourceCulture);

        public static string DictationDoNotDisturbWhiteboard => ResourceManager.GetString(nameof(DictationDoNotDisturbWhiteboard), _resourceCulture);

        public static string DictationDoNotDisturbWhiteboardHint => ResourceManager.GetString(nameof(DictationDoNotDisturbWhiteboardHint), _resourceCulture);

        public static string EnableDynamic => ResourceManager.GetString(nameof(EnableDynamic), _resourceCulture);

        public static string EnableDynamicHint => ResourceManager.GetString(nameof(EnableDynamicHint), _resourceCulture);

        public static string EnableWindowsToast => ResourceManager.GetString(nameof(EnableWindowsToast), _resourceCulture);

        public static string EnableWindowsToastHint => ResourceManager.GetString(nameof(EnableWindowsToastHint), _resourceCulture);

        public static string GroupTitle => ResourceManager.GetString(nameof(GroupTitle), _resourceCulture);

        public static string ImportantDuration => ResourceManager.GetString(nameof(ImportantDuration), _resourceCulture);

        public static string ImportantDurationHint => ResourceManager.GetString(nameof(ImportantDurationHint), _resourceCulture);

        public static string NavTooltip => ResourceManager.GetString(nameof(NavTooltip), _resourceCulture);

        public static string NewVersion => ResourceManager.GetString(nameof(NewVersion), _resourceCulture);

        public static string OtherDuration => ResourceManager.GetString(nameof(OtherDuration), _resourceCulture);

        public static string OtherDurationHint => ResourceManager.GetString(nameof(OtherDurationHint), _resourceCulture);

        public static string Placement => ResourceManager.GetString(nameof(Placement), _resourceCulture);

        public static string PlacementHint => ResourceManager.GetString(nameof(PlacementHint), _resourceCulture);

        public static string PlacementFloatingBarAbove => ResourceManager.GetString(nameof(PlacementFloatingBarAbove), _resourceCulture);

        public static string PlacementTopCenter => ResourceManager.GetString(nameof(PlacementTopCenter), _resourceCulture);

        public static string PlacementTopLeft => ResourceManager.GetString(nameof(PlacementTopLeft), _resourceCulture);

        public static string PlacementTopRight => ResourceManager.GetString(nameof(PlacementTopRight), _resourceCulture);

        public static string Provider_Disabled => ResourceManager.GetString(nameof(Provider_Disabled), _resourceCulture);

        public static string Provider_Local => ResourceManager.GetString(nameof(Provider_Local), _resourceCulture);

        public static string Provider_LocalDesc => ResourceManager.GetString(nameof(Provider_LocalDesc), _resourceCulture);

        public static string Provider_Running => ResourceManager.GetString(nameof(Provider_Running), _resourceCulture);

        public static string Provider_WindowsToast => ResourceManager.GetString(nameof(Provider_WindowsToast), _resourceCulture);

        public static string Provider_WindowsToastDesc => ResourceManager.GetString(nameof(Provider_WindowsToastDesc), _resourceCulture);

        public static string ProviderManagement => ResourceManager.GetString(nameof(ProviderManagement), _resourceCulture);

        public static string ProviderManagementHint => ResourceManager.GetString(nameof(ProviderManagementHint), _resourceCulture);

        public static string ProviderRefresh => ResourceManager.GetString(nameof(ProviderRefresh), _resourceCulture);

        public static string ProviderTitle => ResourceManager.GetString(nameof(ProviderTitle), _resourceCulture);

        public static string ReminderDuration => ResourceManager.GetString(nameof(ReminderDuration), _resourceCulture);

        public static string ReminderDurationHint => ResourceManager.GetString(nameof(ReminderDurationHint), _resourceCulture);

        public static string SettingsTitle => ResourceManager.GetString(nameof(SettingsTitle), _resourceCulture);

        public static string Test => ResourceManager.GetString(nameof(Test), _resourceCulture);

        public static string TestButton => ResourceManager.GetString(nameof(TestButton), _resourceCulture);

        public static string TestHint => ResourceManager.GetString(nameof(TestHint), _resourceCulture);

        public static string TestSummary => ResourceManager.GetString(nameof(TestSummary), _resourceCulture);

        public static string TestText => ResourceManager.GetString(nameof(TestText), _resourceCulture);

        public static string TestTitle => ResourceManager.GetString(nameof(TestTitle), _resourceCulture);

        public static string Type_Important => ResourceManager.GetString(nameof(Type_Important), _resourceCulture);

        public static string Type_Other => ResourceManager.GetString(nameof(Type_Other), _resourceCulture);

        public static string Type_Reminder => ResourceManager.GetString(nameof(Type_Reminder), _resourceCulture);

        public static string Type_Update => ResourceManager.GetString(nameof(Type_Update), _resourceCulture);

        public static string Type_Urgent => ResourceManager.GetString(nameof(Type_Urgent), _resourceCulture);

        public static string UpdateDuration => ResourceManager.GetString(nameof(UpdateDuration), _resourceCulture);

        public static string UpdateDurationHint => ResourceManager.GetString(nameof(UpdateDurationHint), _resourceCulture);

        public static string UpdateTitle => ResourceManager.GetString(nameof(UpdateTitle), _resourceCulture);

        public static string UrgentDuration => ResourceManager.GetString(nameof(UrgentDuration), _resourceCulture);

        public static string UrgentDurationHint => ResourceManager.GetString(nameof(UrgentDurationHint), _resourceCulture);

        public static string ViewDetails => ResourceManager.GetString(nameof(ViewDetails), _resourceCulture);

    }
}