//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from OobeStrings.resx, do not edit manually.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Ink_Canvas.Properties
{
    [CompilerGenerated]
    public static class OobeStrings
    {
        private static ResourceManager _resourceMan;
        private static CultureInfo _resourceCulture;

        public static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(_resourceMan, null))
                {
                    var temp = new ResourceManager("Ink_Canvas.Properties.OobeStrings", typeof(OobeStrings).Assembly);
                    _resourceMan = temp;
                }
                return _resourceMan;
            }
        }

        public static CultureInfo Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        public static string GetString(string key)
        {
            return ResourceManager.GetString(key, _resourceCulture);
        }

        public static string Oobe_WelcomeTitle => ResourceManager.GetString(nameof(Oobe_WelcomeTitle), _resourceCulture);
        public static string Oobe_WelcomeDesc => ResourceManager.GetString(nameof(Oobe_WelcomeDesc), _resourceCulture);
        public static string Oobe_StepCount => ResourceManager.GetString(nameof(Oobe_StepCount), _resourceCulture);
        public static string Oobe_StartStepByStep => ResourceManager.GetString(nameof(Oobe_StartStepByStep), _resourceCulture);
        public static string Oobe_UsePreset => ResourceManager.GetString(nameof(Oobe_UsePreset), _resourceCulture);
        public static string Oobe_NavWelcome => ResourceManager.GetString(nameof(Oobe_NavWelcome), _resourceCulture);
        public static string Oobe_NavCanvas => ResourceManager.GetString(nameof(Oobe_NavCanvas), _resourceCulture);
        public static string Oobe_NavGestures => ResourceManager.GetString(nameof(Oobe_NavGestures), _resourceCulture);
        public static string Oobe_NavPPT => ResourceManager.GetString(nameof(Oobe_NavPPT), _resourceCulture);
        public static string Oobe_NavAutomation => ResourceManager.GetString(nameof(Oobe_NavAutomation), _resourceCulture);
        public static string Oobe_NavAdvanced => ResourceManager.GetString(nameof(Oobe_NavAdvanced), _resourceCulture);
        public static string Oobe_NavFinish => ResourceManager.GetString(nameof(Oobe_NavFinish), _resourceCulture);
        public static string Oobe_StartupCrashTitle => ResourceManager.GetString(nameof(Oobe_StartupCrashTitle), _resourceCulture);
        public static string Oobe_FoldAtStartup => ResourceManager.GetString(nameof(Oobe_FoldAtStartup), _resourceCulture);
        public static string Oobe_FoldAtStartupDesc => ResourceManager.GetString(nameof(Oobe_FoldAtStartupDesc), _resourceCulture);
        public static string Oobe_CrashAction => ResourceManager.GetString(nameof(Oobe_CrashAction), _resourceCulture);
        public static string Oobe_CrashActionDesc => ResourceManager.GetString(nameof(Oobe_CrashActionDesc), _resourceCulture);
        public static string Oobe_CrashSilentRestart => ResourceManager.GetString(nameof(Oobe_CrashSilentRestart), _resourceCulture);
        public static string Oobe_CrashNoAction => ResourceManager.GetString(nameof(Oobe_CrashNoAction), _resourceCulture);
        public static string Oobe_CrashShowDialog => ResourceManager.GetString(nameof(Oobe_CrashShowDialog), _resourceCulture);
        public static string Oobe_Step2Title => ResourceManager.GetString(nameof(Oobe_Step2Title), _resourceCulture);
        public static string Oobe_ShowPenCursorDesc => ResourceManager.GetString(nameof(Oobe_ShowPenCursorDesc), _resourceCulture);
        public static string Oobe_IgnorePressureDesc => ResourceManager.GetString(nameof(Oobe_IgnorePressureDesc), _resourceCulture);
        public static string Oobe_HideInkOnExit => ResourceManager.GetString(nameof(Oobe_HideInkOnExit), _resourceCulture);
        public static string Oobe_HideInkOnExitDesc => ResourceManager.GetString(nameof(Oobe_HideInkOnExitDesc), _resourceCulture);
        public static string Oobe_InkRecogDesc => ResourceManager.GetString(nameof(Oobe_InkRecogDesc), _resourceCulture);
        public static string Oobe_Step3Title => ResourceManager.GetString(nameof(Oobe_Step3Title), _resourceCulture);
        public static string Oobe_EnableTwoFingerZoom => ResourceManager.GetString(nameof(Oobe_EnableTwoFingerZoom), _resourceCulture);
        public static string Oobe_EnableTwoFingerPan => ResourceManager.GetString(nameof(Oobe_EnableTwoFingerPan), _resourceCulture);
        public static string Oobe_PalmEraserDesc => ResourceManager.GetString(nameof(Oobe_PalmEraserDesc), _resourceCulture);
        public static string Oobe_AppTheme => ResourceManager.GetString(nameof(Oobe_AppTheme), _resourceCulture);
        public static string Oobe_AppThemeDesc => ResourceManager.GetString(nameof(Oobe_AppThemeDesc), _resourceCulture);
        public static string Oobe_ThemeLight => ResourceManager.GetString(nameof(Oobe_ThemeLight), _resourceCulture);
        public static string Oobe_ShowSplashScreenDesc => ResourceManager.GetString(nameof(Oobe_ShowSplashScreenDesc), _resourceCulture);
        public static string Oobe_TrayAndQuickPanel => ResourceManager.GetString(nameof(Oobe_TrayAndQuickPanel), _resourceCulture);
        public static string Oobe_EnableTrayIcon => ResourceManager.GetString(nameof(Oobe_EnableTrayIcon), _resourceCulture);
        public static string Oobe_EnableTrayIconDesc => ResourceManager.GetString(nameof(Oobe_EnableTrayIconDesc), _resourceCulture);
        public static string Oobe_EnableQuickPanel => ResourceManager.GetString(nameof(Oobe_EnableQuickPanel), _resourceCulture);
        public static string Oobe_EnableQuickPanelDesc => ResourceManager.GetString(nameof(Oobe_EnableQuickPanelDesc), _resourceCulture);
        public static string Oobe_EnableGlobalHotkeys => ResourceManager.GetString(nameof(Oobe_EnableGlobalHotkeys), _resourceCulture);
        public static string Oobe_EnableGlobalHotkeysDesc => ResourceManager.GetString(nameof(Oobe_EnableGlobalHotkeysDesc), _resourceCulture);
        public static string Oobe_Step5Title => ResourceManager.GetString(nameof(Oobe_Step5Title), _resourceCulture);
        public static string Oobe_EnablePPTLink => ResourceManager.GetString(nameof(Oobe_EnablePPTLink), _resourceCulture);
        public static string Oobe_EnablePPTLinkDesc => ResourceManager.GetString(nameof(Oobe_EnablePPTLinkDesc), _resourceCulture);
        public static string Oobe_AutoSaveStrokes => ResourceManager.GetString(nameof(Oobe_AutoSaveStrokes), _resourceCulture);
        public static string Oobe_AutoSaveStrokesDesc => ResourceManager.GetString(nameof(Oobe_AutoSaveStrokesDesc), _resourceCulture);
        public static string Oobe_AutoScreenshot => ResourceManager.GetString(nameof(Oobe_AutoScreenshot), _resourceCulture);
        public static string Oobe_AutoScreenshotDesc => ResourceManager.GetString(nameof(Oobe_AutoScreenshotDesc), _resourceCulture);
        public static string Oobe_EnableTimeCapsule => ResourceManager.GetString(nameof(Oobe_EnableTimeCapsule), _resourceCulture);
        public static string Oobe_EnableTimeCapsuleDesc => ResourceManager.GetString(nameof(Oobe_EnableTimeCapsuleDesc), _resourceCulture);
        public static string Oobe_Step6Title => ResourceManager.GetString(nameof(Oobe_Step6Title), _resourceCulture);
        public static string Oobe_AutoFoldInPPT => ResourceManager.GetString(nameof(Oobe_AutoFoldInPPT), _resourceCulture);
        public static string Oobe_AutoSaveInk => ResourceManager.GetString(nameof(Oobe_AutoSaveInk), _resourceCulture);
        public static string Oobe_AutoSaveInkDesc => ResourceManager.GetString(nameof(Oobe_AutoSaveInkDesc), _resourceCulture);
        public static string Oobe_FloatingInterceptorDesc => ResourceManager.GetString(nameof(Oobe_FloatingInterceptorDesc), _resourceCulture);
        public static string Oobe_ScreenshotTitle => ResourceManager.GetString(nameof(Oobe_ScreenshotTitle), _resourceCulture);
        public static string Oobe_AutoSaveScreenshot => ResourceManager.GetString(nameof(Oobe_AutoSaveScreenshot), _resourceCulture);
        public static string Oobe_SaveByDate => ResourceManager.GetString(nameof(Oobe_SaveByDate), _resourceCulture);
        public static string Oobe_ShowRollCallButtons => ResourceManager.GetString(nameof(Oobe_ShowRollCallButtons), _resourceCulture);
        public static string Oobe_Step8Title => ResourceManager.GetString(nameof(Oobe_Step8Title), _resourceCulture);
        public static string Oobe_EnableLog => ResourceManager.GetString(nameof(Oobe_EnableLog), _resourceCulture);
        public static string Oobe_EnableLogDesc => ResourceManager.GetString(nameof(Oobe_EnableLogDesc), _resourceCulture);
        public static string Oobe_FinishTitle => ResourceManager.GetString(nameof(Oobe_FinishTitle), _resourceCulture);
        public static string Oobe_FinishDesc => ResourceManager.GetString(nameof(Oobe_FinishDesc), _resourceCulture);
        public static string Oobe_SummaryPPTLink => ResourceManager.GetString(nameof(Oobe_SummaryPPTLink), _resourceCulture);
        public static string Oobe_SummaryTrayIcon => ResourceManager.GetString(nameof(Oobe_SummaryTrayIcon), _resourceCulture);
        public static string Oobe_BoolEnabled => ResourceManager.GetString(nameof(Oobe_BoolEnabled), _resourceCulture);
        public static string Oobe_BoolDisabled => ResourceManager.GetString(nameof(Oobe_BoolDisabled), _resourceCulture);
        public static string Oobe_Previous => ResourceManager.GetString(nameof(Oobe_Previous), _resourceCulture);
        public static string Oobe_Next => ResourceManager.GetString(nameof(Oobe_Next), _resourceCulture);
        public static string Oobe_SaveAndStart => ResourceManager.GetString(nameof(Oobe_SaveAndStart), _resourceCulture);
        public static string Oobe_StepFormat => ResourceManager.GetString(nameof(Oobe_StepFormat), _resourceCulture);
        public static string Oobe_StepFinishFormat => ResourceManager.GetString(nameof(Oobe_StepFinishFormat), _resourceCulture);
        public static string Oobe_PresetTitle => ResourceManager.GetString(nameof(Oobe_PresetTitle), _resourceCulture);
        public static string Oobe_PresetSubtitle => ResourceManager.GetString(nameof(Oobe_PresetSubtitle), _resourceCulture);
        public static string Oobe_PresetStandard => ResourceManager.GetString(nameof(Oobe_PresetStandard), _resourceCulture);
        public static string Oobe_PresetStandardDesc => ResourceManager.GetString(nameof(Oobe_PresetStandardDesc), _resourceCulture);
        public static string Oobe_PresetLite => ResourceManager.GetString(nameof(Oobe_PresetLite), _resourceCulture);
        public static string Oobe_PresetLiteDesc => ResourceManager.GetString(nameof(Oobe_PresetLiteDesc), _resourceCulture);
        public static string Oobe_PresetTagPPTLink => ResourceManager.GetString(nameof(Oobe_PresetTagPPTLink), _resourceCulture);
        public static string Oobe_PresetTagTwoFinger => ResourceManager.GetString(nameof(Oobe_PresetTagTwoFinger), _resourceCulture);
        public static string Oobe_PresetTagTrayIcon => ResourceManager.GetString(nameof(Oobe_PresetTagTrayIcon), _resourceCulture);
        public static string Oobe_PresetNote => ResourceManager.GetString(nameof(Oobe_PresetNote), _resourceCulture);
        public static string Oobe_PresetBack => ResourceManager.GetString(nameof(Oobe_PresetBack), _resourceCulture);
        public static string Oobe_PresetApply => ResourceManager.GetString(nameof(Oobe_PresetApply), _resourceCulture);
        public static string Oobe_Step2Subtitle => ResourceManager.GetString(nameof(Oobe_Step2Subtitle), _resourceCulture);
        public static string Oobe_Step3Subtitle => ResourceManager.GetString(nameof(Oobe_Step3Subtitle), _resourceCulture);
        public static string Oobe_Step4Subtitle => ResourceManager.GetString(nameof(Oobe_Step4Subtitle), _resourceCulture);
        public static string Oobe_Step5Subtitle => ResourceManager.GetString(nameof(Oobe_Step5Subtitle), _resourceCulture);
        public static string Oobe_Step6Subtitle => ResourceManager.GetString(nameof(Oobe_Step6Subtitle), _resourceCulture);
        public static string Oobe_Step7Subtitle => ResourceManager.GetString(nameof(Oobe_Step7Subtitle), _resourceCulture);
        public static string Oobe_Step8Subtitle => ResourceManager.GetString(nameof(Oobe_Step8Subtitle), _resourceCulture);
        public static string Oobe_SummaryAppTheme => ResourceManager.GetString(nameof(Oobe_SummaryAppTheme), _resourceCulture);
        public static string Oobe_SummaryTwoFingerZoom => ResourceManager.GetString(nameof(Oobe_SummaryTwoFingerZoom), _resourceCulture);
        public static string Oobe_SummaryLogEnabled => ResourceManager.GetString(nameof(Oobe_SummaryLogEnabled), _resourceCulture);
    }
}
