//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from PPTStrings.resx, do not edit manually.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Ink_Canvas.Properties
{
    [CompilerGenerated]
    public static class PPTStrings
    {
        private static ResourceManager _resourceMan;
        private static CultureInfo _resourceCulture;

        public static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(_resourceMan, null))
                {
                    var temp = new ResourceManager("Ink_Canvas.Properties.PPTStrings", typeof(PPTStrings).Assembly);
                    _resourceMan = temp;
                }
                return _resourceMan;
            }
        }

        public static CultureInfo Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        public static string GetString(string key)
        {
            return ResourceManager.GetString(key, _resourceCulture);
        }

        public static string AutoSaveStrokes => ResourceManager.GetString(nameof(AutoSaveStrokes), _resourceCulture);

        public static string AutoSaveStrokesHint => ResourceManager.GetString(nameof(AutoSaveStrokesHint), _resourceCulture);

        public static string AutoScreenshot => ResourceManager.GetString(nameof(AutoScreenshot), _resourceCulture);

        public static string AutoScreenshotHint => ResourceManager.GetString(nameof(AutoScreenshotHint), _resourceCulture);

        public static string BlackBackground => ResourceManager.GetString(nameof(BlackBackground), _resourceCulture);

        public static string BottomGroupTitle => ResourceManager.GetString(nameof(BottomGroupTitle), _resourceCulture);

        public static string EnhancedPreview => ResourceManager.GetString(nameof(EnhancedPreview), _resourceCulture);

        public static string EnhancedPreviewHint => ResourceManager.GetString(nameof(EnhancedPreviewHint), _resourceCulture);

        public static string EnhancedPreviewLoadingAnimation => ResourceManager.GetString(nameof(EnhancedPreviewLoadingAnimation), _resourceCulture);

        public static string EnhancedPreviewLoadingAnimationHint => ResourceManager.GetString(nameof(EnhancedPreviewLoadingAnimationHint), _resourceCulture);

        public static string LoadingPPT => ResourceManager.GetString(nameof(LoadingPPT), _resourceCulture);

        public static string EnterAnnotationOnShow => ResourceManager.GetString(nameof(EnterAnnotationOnShow), _resourceCulture);

        public static string FingerGestureSlide => ResourceManager.GetString(nameof(FingerGestureSlide), _resourceCulture);

        public static string FingerGestureSlideHint => ResourceManager.GetString(nameof(FingerGestureSlideHint), _resourceCulture);

        public static string FlipButtonsTitle => ResourceManager.GetString(nameof(FlipButtonsTitle), _resourceCulture);

        public static string FlipButtonsScale => ResourceManager.GetString(nameof(FlipButtonsScale), _resourceCulture);

        public static string GoToFirstPageOnReenter => ResourceManager.GetString(nameof(GoToFirstPageOnReenter), _resourceCulture);

        public static string GroupTitle => ResourceManager.GetString(nameof(GroupTitle), _resourceCulture);

        public static string HalfOpacity => ResourceManager.GetString(nameof(HalfOpacity), _resourceCulture);

        public static string KillWppHint => ResourceManager.GetString(nameof(KillWppHint), _resourceCulture);

        public static string KillWppProcess => ResourceManager.GetString(nameof(KillWppProcess), _resourceCulture);

        public static string LeftBottomOffset => ResourceManager.GetString(nameof(LeftBottomOffset), _resourceCulture);

        public static string LeftBottomOpacity => ResourceManager.GetString(nameof(LeftBottomOpacity), _resourceCulture);

        public static string LeftOffset => ResourceManager.GetString(nameof(LeftOffset), _resourceCulture);

        public static string LeftOpacity => ResourceManager.GetString(nameof(LeftOpacity), _resourceCulture);

        public static string LongPressPageTurn => ResourceManager.GetString(nameof(LongPressPageTurn), _resourceCulture);

        public static string LongPressPageTurnHint => ResourceManager.GetString(nameof(LongPressPageTurnHint), _resourceCulture);

        public static string NotifyAutoPlay => ResourceManager.GetString(nameof(NotifyAutoPlay), _resourceCulture);

        public static string NotifyHiddenPage => ResourceManager.GetString(nameof(NotifyHiddenPage), _resourceCulture);

        public static string PageButtonClickable => ResourceManager.GetString(nameof(PageButtonClickable), _resourceCulture);

        public static string PageButtonClickableHint => ResourceManager.GetString(nameof(PageButtonClickableHint), _resourceCulture);

        public static string Position_Left => ResourceManager.GetString(nameof(Position_Left), _resourceCulture);

        public static string Position_LeftBottom => ResourceManager.GetString(nameof(Position_LeftBottom), _resourceCulture);

        public static string Position_Right => ResourceManager.GetString(nameof(Position_Right), _resourceCulture);

        public static string Position_RightBottom => ResourceManager.GetString(nameof(Position_RightBottom), _resourceCulture);

        public static string RememberLastPage => ResourceManager.GetString(nameof(RememberLastPage), _resourceCulture);

        public static string RememberLastPageHint => ResourceManager.GetString(nameof(RememberLastPageHint), _resourceCulture);

        public static string RightBottomOffset => ResourceManager.GetString(nameof(RightBottomOffset), _resourceCulture);

        public static string RightBottomOpacity => ResourceManager.GetString(nameof(RightBottomOpacity), _resourceCulture);

        public static string RightOffset => ResourceManager.GetString(nameof(RightOffset), _resourceCulture);

        public static string RightOpacity => ResourceManager.GetString(nameof(RightOpacity), _resourceCulture);

        public static string ShowFlipButtons => ResourceManager.GetString(nameof(ShowFlipButtons), _resourceCulture);

        public static string ShowPageNumber => ResourceManager.GetString(nameof(ShowPageNumber), _resourceCulture);

        public static string ShowQuickPanelInShow => ResourceManager.GetString(nameof(ShowQuickPanelInShow), _resourceCulture);

        public static string ShowQuickPanelInShowHint => ResourceManager.GetString(nameof(ShowQuickPanelInShowHint), _resourceCulture);

        public static string SideGroupTitle => ResourceManager.GetString(nameof(SideGroupTitle), _resourceCulture);

        public static string SkipAnimations => ResourceManager.GetString(nameof(SkipAnimations), _resourceCulture);

        public static string SupportPowerPoint => ResourceManager.GetString(nameof(SupportPowerPoint), _resourceCulture);

        public static string SupportWPS => ResourceManager.GetString(nameof(SupportWPS), _resourceCulture);

        public static string TimeCapsule => ResourceManager.GetString(nameof(TimeCapsule), _resourceCulture);

        public static string TimeCapsuleHint => ResourceManager.GetString(nameof(TimeCapsuleHint), _resourceCulture);

        public static string TimeCapsuleOpacity => ResourceManager.GetString(nameof(TimeCapsuleOpacity), _resourceCulture);

        public static string TimeCapsulePos_Center => ResourceManager.GetString(nameof(TimeCapsulePos_Center), _resourceCulture);

        public static string TimeCapsulePos_TL => ResourceManager.GetString(nameof(TimeCapsulePos_TL), _resourceCulture);

        public static string TimeCapsulePos_TR => ResourceManager.GetString(nameof(TimeCapsulePos_TR), _resourceCulture);

        public static string TimeCapsulePosition => ResourceManager.GetString(nameof(TimeCapsulePosition), _resourceCulture);

        public static string TimeCapsuleResetPosition => ResourceManager.GetString(nameof(TimeCapsuleResetPosition), _resourceCulture);

        public static string TimeCapsuleResetPositionHint => ResourceManager.GetString(nameof(TimeCapsuleResetPositionHint), _resourceCulture);

        public static string TimeCapsuleScale => ResourceManager.GetString(nameof(TimeCapsuleScale), _resourceCulture);

        public static string TwoFingerGesture => ResourceManager.GetString(nameof(TwoFingerGesture), _resourceCulture);

        public static string UseRot => ResourceManager.GetString(nameof(UseRot), _resourceCulture);

        public static string PPTQuickPanel_Sound => ResourceManager.GetString(nameof(PPTQuickPanel_Sound), _resourceCulture);

        public static string PPTQuickPanel_Insert => ResourceManager.GetString(nameof(PPTQuickPanel_Insert), _resourceCulture);

        public static string PPTQuickPanel_ScreenshotInsert => ResourceManager.GetString(nameof(PPTQuickPanel_ScreenshotInsert), _resourceCulture);

        public static string PPTQuickPanel_FocusMagnifier => ResourceManager.GetString(nameof(PPTQuickPanel_FocusMagnifier), _resourceCulture);

        public static string PPTQuickPanel_OpenMagnifier => ResourceManager.GetString(nameof(PPTQuickPanel_OpenMagnifier), _resourceCulture);

        public static string PPTQuickPanel_Zoom => ResourceManager.GetString(nameof(PPTQuickPanel_Zoom), _resourceCulture);

        public static string PPTQuickPanel_MagnifierHint => ResourceManager.GetString(nameof(PPTQuickPanel_MagnifierHint), _resourceCulture);

        public static string PPTQuickPanel_CloseMagnifier => ResourceManager.GetString(nameof(PPTQuickPanel_CloseMagnifier), _resourceCulture);

        public static string PPT_RememberLastPage_Prompt => ResourceManager.GetString(nameof(PPT_RememberLastPage_Prompt), _resourceCulture);

        public static string PPT_HiddenSlides_Detected => ResourceManager.GetString(nameof(PPT_HiddenSlides_Detected), _resourceCulture);

        public static string PPT_AutoPlay_Detected => ResourceManager.GetString(nameof(PPT_AutoPlay_Detected), _resourceCulture);

        public static string PPT_ModePrompt_Message => ResourceManager.GetString(nameof(PPT_ModePrompt_Message), _resourceCulture);

        public static string PPT_ModePrompt_Setting => ResourceManager.GetString(nameof(PPT_ModePrompt_Setting), _resourceCulture);

        public static string PPT_ModePrompt_SettingHint => ResourceManager.GetString(nameof(PPT_ModePrompt_SettingHint), _resourceCulture);

        public static string PPT_ModePrompt_Title => ResourceManager.GetString(nameof(PPT_ModePrompt_Title), _resourceCulture);

        public static string PPT_SlidesNotFound => ResourceManager.GetString(nameof(PPT_SlidesNotFound), _resourceCulture);

        public static string SmartMode => ResourceManager.GetString(nameof(SmartMode), _resourceCulture);

        public static string SmartModeHint => ResourceManager.GetString(nameof(SmartModeHint), _resourceCulture);
    }
}